FROM docker.io/oven/bun:1.3.10-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production --ignore-scripts && \
    rm -rf ~/.bun/install/cache

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY prisma ./prisma
COPY prisma.config.ts ./
COPY src ./src
COPY tsconfig.json ./
ENV DATABASE_URL="postgresql://localhost:5432/dummy"
ENV NODE_ENV=production
RUN bunx prisma generate
RUN bun build src/server.ts --minify --compile --outfile server

FROM alpine:3.23.3 AS runner

RUN apk add --no-cache \
      openssl \
      ca-certificates \
      libgcc \
      libstdc++ && \
    rm -rf /var/cache/apk/* /usr/share/apk

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 bunuser

WORKDIR /app

RUN mkdir -p /app/tmp && chown bunuser:nodejs /app/tmp

COPY --from=builder --chown=bunuser:nodejs /app/server ./server
COPY --from=builder --chown=bunuser:nodejs /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder --chown=bunuser:nodejs /app/prisma ./prisma

ENV NODE_ENV=production
ENV TMPDIR=/app/tmp

USER bunuser
EXPOSE 4000

CMD ["./server"]