FROM docker.io/oven/bun:1.3.10-alpine AS base
WORKDIR /app

FROM base AS builder
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY src ./src
COPY tsconfig.json ./
ENV NODE_ENV=production
RUN bun build src/server.ts --minify --compile --outfile server

FROM alpine:3.23.3 AS runner

RUN apk add --no-cache \
      openssl ca-certificates libgcc libstdc++ && \
    rm -rf /var/cache/apk/* /usr/share/apk

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 bunuser

WORKDIR /app

RUN mkdir -p /app/tmp && chown bunuser:nodejs /app/tmp

COPY --from=builder --chown=bunuser:nodejs /app/server ./server

ENV NODE_ENV=production
ENV TMPDIR=/app/tmp

USER bunuser
EXPOSE 4000

HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --no-verbose --tries=1 --spider http://localhost:4000/ || exit 1

CMD ["./server"]