name: Deploy Web App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          verify-signature: true
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false

      - name: Build Web App
        working-directory: app
        env:
          GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
        run: |
          chmod +x ./gradlew
          ./gradlew :web:wasmJsBrowserDistribution --no-configuration-cache -Pkotlin.native.ignoreDisabledTargets=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: github-pages
          path: app/web/build/dist/wasmJs/productionExecutable/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
